package com.trycore.quotizo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FinancialParameterTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFinancialParameterTypeAllPropertiesEquals(FinancialParameterType expected, FinancialParameterType actual) {
        assertFinancialParameterTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertFinancialParameterTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFinancialParameterTypeAllUpdatablePropertiesEquals(
        FinancialParameterType expected,
        FinancialParameterType actual
    ) {
        assertFinancialParameterTypeUpdatableFieldsEquals(expected, actual);
        assertFinancialParameterTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFinancialParameterTypeAutoGeneratedPropertiesEquals(
        FinancialParameterType expected,
        FinancialParameterType actual
    ) {
        assertThat(expected)
            .as("Verify FinancialParameterType auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFinancialParameterTypeUpdatableFieldsEquals(FinancialParameterType expected, FinancialParameterType actual) {
        assertThat(expected)
            .as("Verify FinancialParameterType relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getActive()).as("check active").isEqualTo(actual.getActive()))
            .satisfies(e -> assertThat(e.getCreatedBy()).as("check createdBy").isEqualTo(actual.getCreatedBy()))
            .satisfies(e -> assertThat(e.getCreatedDate()).as("check createdDate").isEqualTo(actual.getCreatedDate()))
            .satisfies(e -> assertThat(e.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(actual.getLastModifiedBy()))
            .satisfies(e -> assertThat(e.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(actual.getLastModifiedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFinancialParameterTypeUpdatableRelationshipsEquals(
        FinancialParameterType expected,
        FinancialParameterType actual
    ) {}
}
